### ISSUE TITLE
Example for POST

### ISSUE THREAD

**Issue by RupenAnjaria** [msathis/node-http-ntlm#2]
Can we please have some more example on how to use POST method and send body?

I tried below but seems not working:
```javascript
const ntlmOptions = {
        url: 'http://myhost.com/api_path',
        username:'username123',
        password:'Password123',
        workstation: '',
        domain: '',
        body:
          { queryString: '?Field1=val1&Field2=val2',
            data: { user1: 'name1', user2: 'name2' } },
        request: {
          headers: {
            'Content-Type': 'application/json'
          },
          method:'POST',
        },
    };
```

**Comment by msathis** [comment]
Hi @RupenAnjaria . Sorry. I'm not actively working on this. I dont have ntlm server to test also. Can you please debug and send me the PR?

**Comment by ultimate-tester** [comment]
Hi @RupenAnjaria I succesfully posted using this module using multiple approaches (json, formdata, etc.).
The posting goes exactly the same as the original "request" module and didn't give any problem for me.
There are some problems I see with your code:

1) "body" should be inside the "request" key
2) "body" can not contain "queryString"
3) "queryString" does not exist
4) "queryString" should probably be replaced by the "qs" option of request
3) You probably want to use "formData" option instead of the "body" option (to send it as multipart/form-data) or use the "json" option (to send it as raw json data). I assume the last because you set the Content-Type to "application/json"

Here is the new code that should work:

```
const ntlmOptions = {
    url: 'http://myhost.com/api_path',
    username: 'username123',
    password: 'Password123',
    workstation: '',
    domain: '',
    request: {
        method: 'POST',
        qs: {'Field1': 'val1', 'Field2': 'val2'},
        json: {user1: 'name1', user2: 'name2'},
        headers: {
            'Content-Type': 'application/json'
        }
    }
};
```

**Comment by RupenAnjaria** [comment]
it's working.

**Comment by RupenAnjaria** [comment]
Thank you @ultimate-tester
